# Generated by Django 3.0.7 on 2020-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeAfricaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('duree', models.CharField(blank=True, max_length=250, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('myimage', models.FileField(blank=True, null=True, upload_to='africafimes')),
                ('lien_detail', models.URLField(blank=True, null=True)),
                ('lien_lien', models.URLField()),
                ('types', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FilmeAfricaine',
                'verbose_name_plural': 'FilmeAfricaines',
            },
        ),
    ]
